// ==================== RISK ASSESSMENT QUESTIONS ====================
// All questions in English based on the comprehensive risk assessment framework

import type { 
  RiskCapacityQuestion, 
  RiskWillingnessQuestion, 
  BehavioralBiasQuestion 
} from './types';

// ==================== PART 1: RISK CAPACITY (10 Questions) ====================
// Measures objective ability to take risk

export const riskCapacityQuestions: RiskCapacityQuestion[] = [
  {
    id: 1,
    key: 'q1_emergency_fund',
    title: 'Emergency Fund',
    question: 'If your main income were to stop, how many months of essential living expenses could your current cash savings cover?',
    weight: 3,
    icon: '⚡',
    whyImportant: 'Without an emergency fund, any financial risk could be catastrophic. This is your first line of defense against financial crises.',
    options: [
      { value: 1, label: 'Less than 1 month' },
      { value: 2, label: '1 to 3 months' },
      { value: 3, label: '3 to 6 months' },
      { value: 4, label: '6 to 12 months' },
      { value: 5, label: '12 months or more' },
    ],
  },
  {
    id: 2,
    key: 'q2_income_stability',
    title: 'Income Stability',
    question: 'How stable and predictable is your income in terms of amount and continuity?',
    weight: 2,
    icon: '💰',
    whyImportant: 'Unstable income = need for more liquidity = lower risk capacity.',
    options: [
      { value: 1, label: 'Very unstable and unpredictable (freelance, commission-based)' },
      { value: 2, label: 'Somewhat unstable (variable income)' },
      { value: 3, label: 'Moderately stable (fixed salary with fluctuations)' },
      { value: 4, label: 'Stable (fixed monthly salary)' },
      { value: 5, label: 'Very stable and predictable (permanent employment + additional income sources)' },
    ],
  },
  {
    id: 3,
    key: 'q3_investment_to_income_ratio',
    title: 'Investment to Annual Income Ratio',
    question: 'What percentage of your annual net income is the amount you plan to invest?',
    weight: 3,
    icon: '📊',
    whyImportant: 'Higher investment relative to income means higher stakes if losses occur.',
    options: [
      { value: 1, label: 'More than 100% (Very high risk)', description: 'Investing more than a full year\'s income' },
      { value: 2, label: '50% to 100%' },
      { value: 3, label: '25% to 50%' },
      { value: 4, label: '10% to 25%' },
      { value: 5, label: 'Less than 10% (Very low risk)' },
    ],
  },
  {
    id: 4,
    key: 'q4_investment_horizon',
    title: 'Investment Time Horizon',
    question: 'How many years can you keep this money invested without needing to withdraw it?',
    weight: 2,
    icon: '📅',
    whyImportant: 'Longer time horizon = opportunity to recover from downturns = higher risk capacity.',
    options: [
      { value: 1, label: 'Less than 1 year' },
      { value: 2, label: '1 to 3 years' },
      { value: 3, label: '3 to 5 years' },
      { value: 4, label: '5 to 10 years' },
      { value: 5, label: 'More than 10 years' },
    ],
  },
  {
    id: 5,
    key: 'q5_liquidity_needs',
    title: 'Liquidity Needs',
    question: 'What is the likelihood that you will need a significant portion of this money within the next 2 years?',
    weight: 2,
    icon: '💧',
    whyImportant: 'High liquidity needs = cannot invest in illiquid assets.',
    options: [
      { value: 1, label: 'Very high (almost certain)' },
      { value: 2, label: 'High' },
      { value: 3, label: 'Moderate (possible)' },
      { value: 4, label: 'Low' },
      { value: 5, label: 'Very low (no plans at all)' },
    ],
  },
  {
    id: 6,
    key: 'q6_debt_ratio',
    title: 'Debt Status',
    question: 'What percentage of your total debt payments (loans, mortgages, credit cards) is relative to your monthly income?',
    weight: 3,
    icon: '💳',
    whyImportant: 'High debt = financial pressure = low risk capacity.',
    options: [
      { value: 1, label: 'More than 50% of income goes to debt payments' },
      { value: 2, label: '30% to 50%' },
      { value: 3, label: '15% to 30%' },
      { value: 4, label: '5% to 15%' },
      { value: 5, label: 'Less than 5% or no debt' },
    ],
  },
  {
    id: 7,
    key: 'q7_age',
    title: 'Age Group',
    question: 'What is your age group?',
    weight: 1,
    icon: '🎂',
    whyImportant: 'Younger age = more time to recover from losses.',
    options: [
      { value: 1, label: 'Over 60 years old' },
      { value: 2, label: '50 to 60 years old' },
      { value: 3, label: '40 to 50 years old' },
      { value: 4, label: '30 to 40 years old' },
      { value: 5, label: 'Under 30 years old' },
    ],
  },
  {
    id: 8,
    key: 'q8_dependents',
    title: 'Financial Dependents',
    question: 'How many people are financially dependent on you?',
    weight: 1,
    icon: '👨‍👩‍👧‍👦',
    whyImportant: 'More dependents = more responsibility = lower risk capacity.',
    options: [
      { value: 1, label: '4 or more people' },
      { value: 2, label: '3 people' },
      { value: 3, label: '2 people' },
      { value: 4, label: '1 person' },
      { value: 5, label: 'No one' },
    ],
  },
  {
    id: 9,
    key: 'q9_insurance_coverage',
    title: 'Insurance & Financial Protection',
    question: 'What is your insurance and financial protection coverage?',
    weight: 1,
    icon: '🛡️',
    whyImportant: 'Insurance = protection against financial shocks = higher risk capacity.',
    options: [
      { value: 1, label: 'No insurance at all' },
      { value: 2, label: 'Basic health insurance only' },
      { value: 3, label: 'Health + life or accident insurance' },
      { value: 4, label: 'Comprehensive coverage (health, life, property)' },
      { value: 5, label: 'Comprehensive coverage + investment-linked insurance' },
    ],
  },
  {
    id: 10,
    key: 'q10_investment_experience',
    title: 'Investment Experience',
    question: 'What is your level of investment experience?',
    weight: 2,
    icon: '📈',
    whyImportant: 'More experience = better understanding of risk = better management.',
    options: [
      { value: 1, label: 'No experience at all' },
      { value: 2, label: 'Bank deposits only' },
      { value: 3, label: 'Bank deposits + mutual funds' },
      { value: 4, label: 'Stocks, bonds, and funds' },
      { value: 5, label: 'Diversified portfolio + advanced instruments (derivatives, crypto)' },
    ],
  },
];

// ==================== PART 2: RISK WILLINGNESS (10 Questions) ====================
// Measures psychological readiness to take risk

export const riskWillingnessQuestions: RiskWillingnessQuestion[] = [
  {
    id: 11,
    key: 'q11_reaction_to_20_drop',
    title: 'Reaction to 20% Drop',
    question: 'If your investment value dropped by 20% over 3 months, what would you do?',
    icon: '📉',
    options: [
      { value: 1, label: 'Sell everything immediately and exit the market' },
      { value: 2, label: 'Sell a large portion to prevent further losses' },
      { value: 3, label: 'Wait and see what happens' },
      { value: 4, label: 'Make no changes and hold' },
      { value: 5, label: 'See it as a buying opportunity and invest more' },
    ],
  },
  {
    id: 12,
    key: 'q12_max_tolerable_loss',
    title: 'Maximum Tolerable Loss',
    question: 'What is the maximum portfolio value decline you could tolerate without severe stress?',
    icon: '😰',
    options: [
      { value: 1, label: '5% or less' },
      { value: 2, label: '5% to 10%' },
      { value: 3, label: '10% to 20%' },
      { value: 4, label: '20% to 30%' },
      { value: 5, label: 'More than 30%' },
    ],
  },
  {
    id: 13,
    key: 'q13_return_preference',
    title: 'Return Preference',
    question: 'Which return scenario would you prefer?',
    icon: '🎯',
    options: [
      { value: 1, label: '5% guaranteed annual return' },
      { value: 2, label: '50% chance of 8% gain or 2% loss' },
      { value: 3, label: '50% chance of 15% gain or 5% loss' },
      { value: 4, label: '50% chance of 25% gain or 10% loss' },
      { value: 5, label: '50% chance of 50% gain or 20% loss' },
    ],
  },
  {
    id: 14,
    key: 'q14_reaction_to_30_gain',
    title: 'Reaction to 30% Gain',
    question: 'If your investment has gained 30%, what would you do?',
    icon: '🚀',
    options: [
      { value: 1, label: 'Sell immediately and "lock in" the profit' },
      { value: 2, label: 'Sell half of it' },
      { value: 3, label: 'Do nothing and hold' },
      { value: 4, label: 'Hold and wait for more gains' },
      { value: 5, label: 'Add more capital because the trend is positive' },
    ],
  },
  {
    id: 15,
    key: 'q15_diversification_preference',
    title: 'Diversification vs Concentration',
    question: 'Regarding portfolio diversification, which approach do you prefer?',
    icon: '🥧',
    options: [
      { value: 1, label: 'Put all money in one place for higher returns' },
      { value: 2, label: 'Mostly concentrated with some diversification' },
      { value: 3, label: '50-50 between concentration and diversification' },
      { value: 4, label: 'Spread money across several different options' },
      { value: 5, label: 'Maximum diversification (10+ different assets)' },
    ],
  },
  {
    id: 16,
    key: 'q16_market_volatility_reaction',
    title: 'Market Volatility Reaction',
    question: 'When market news is negative and prices are falling, how do you feel?',
    icon: '😟',
    options: [
      { value: 1, label: 'Very stressed, can\'t focus on my work' },
      { value: 2, label: 'Worried and constantly checking prices' },
      { value: 3, label: 'Uncomfortable but continue with daily life' },
      { value: 4, label: 'Not much affected' },
      { value: 5, label: 'No stress at all, this is part of the market' },
    ],
  },
  {
    id: 17,
    key: 'q17_uncertainty_comfort',
    title: 'Comfort with Uncertainty',
    question: 'How do you feel about the future of your investments?',
    icon: '❓',
    options: [
      { value: 1, label: 'Must know exactly what will happen, uncertainty is hard for me' },
      { value: 2, label: 'Prefer to be relatively certain' },
      { value: 3, label: 'Can handle moderate uncertainty' },
      { value: 4, label: 'Can tolerate significant uncertainty' },
      { value: 5, label: 'Completely comfortable with uncertainty, that\'s the nature of markets' },
    ],
  },
  {
    id: 18,
    key: 'q18_investment_goal_priority',
    title: 'Investment Goal Priority',
    question: 'What is your most important investment goal?',
    icon: '🎯',
    options: [
      { value: 1, label: 'Capital preservation (don\'t want any losses)' },
      { value: 2, label: 'Stable income (regular, predictable returns)' },
      { value: 3, label: 'Moderate growth (balance between safety and growth)' },
      { value: 4, label: 'High growth (willing to take risk for more return)' },
      { value: 5, label: 'Maximum growth (want the highest possible returns)' },
    ],
  },
  {
    id: 19,
    key: 'q19_past_loss_experience',
    title: 'Past Loss Experience',
    question: 'If you have experienced investment losses before, how did you feel?',
    icon: '💔',
    options: [
      { value: 1, label: 'Very upset and don\'t want to invest anymore' },
      { value: 2, label: 'Upset and became much more cautious' },
      { value: 3, label: 'Learned from it and continued more carefully' },
      { value: 4, label: 'Accepted it as part of the process' },
      { value: 5, label: 'Saw it as a learning opportunity and continued fearlessly / Never experienced loss' },
    ],
  },
  {
    id: 20,
    key: 'q20_financial_knowledge_self_assessment',
    title: 'Financial Knowledge Self-Assessment',
    question: 'How would you rate your knowledge and understanding of financial markets and investing?',
    icon: '📚',
    options: [
      { value: 1, label: 'Very low, know almost nothing' },
      { value: 2, label: 'Basic, only understand simple concepts' },
      { value: 3, label: 'Moderate, have general knowledge' },
      { value: 4, label: 'Good, can do simple analysis' },
      { value: 5, label: 'Excellent, can do complex analysis' },
    ],
  },
];

// ==================== PART 3: BEHAVIORAL BIASES (5 Questions) ====================
// Measures behavioral biases indirectly (reverse scoring)

export const behavioralBiasQuestions: BehavioralBiasQuestion[] = [
  {
    id: 21,
    key: 'q21_decision_confidence',
    title: 'Decision Confidence',
    biasType: 'overconfidence',
    question: 'When making investment decisions, how much do you trust your own judgment versus professional advisors?',
    icon: '🧠',
    note: 'Reverse scoring - Score 1 = High Overconfidence',
    options: [
      { value: 1, label: 'Completely trust my own judgment, don\'t need advice' },
      { value: 2, label: 'Trust my own analysis more' },
      { value: 3, label: 'Combine my opinion with expert advice' },
      { value: 4, label: 'Mostly consult with experts' },
      { value: 5, label: 'Strongly rely on professional advisors' },
    ],
  },
  {
    id: 22,
    key: 'q22_loss_vs_gain_focus',
    title: 'Loss vs Gain Focus',
    biasType: 'loss_aversion',
    question: 'When reviewing your investment portfolio performance, what do you focus on most?',
    icon: '👁️',
    note: 'Reverse scoring - Score 5 = High Loss Aversion',
    options: [
      { value: 1, label: 'Focus only on total returns and long-term goals' },
      { value: 2, label: 'Focus slightly more on gains' },
      { value: 3, label: 'Look at both equally' },
      { value: 4, label: 'Pay more attention to losses' },
      { value: 5, label: 'Focus mostly on losses and worry about them' },
    ],
  },
  {
    id: 23,
    key: 'q23_investment_idea_sources',
    title: 'Investment Idea Sources',
    biasType: 'herding',
    question: 'What is your main source of investment ideas?',
    icon: '💡',
    note: 'Reverse scoring - Score 5 = High Herding',
    options: [
      { value: 1, label: 'Completely independent research' },
      { value: 2, label: 'Mostly my own research' },
      { value: 3, label: 'Combination of market trends and personal research' },
      { value: 4, label: 'Popular trends and social media' },
      { value: 5, label: 'What most people or friends are doing' },
    ],
  },
  {
    id: 24,
    key: 'q24_selling_decision',
    title: 'Selling Decision',
    biasType: 'disposition_effect',
    question: 'How do you decide when to sell an investment?',
    icon: '💹',
    note: 'Reverse scoring - Score 5 = High Disposition Effect',
    options: [
      { value: 1, label: 'Strict rules based on pre-set strategy, regardless of emotions' },
      { value: 2, label: 'Based on target price, regardless of profit or loss' },
      { value: 3, label: 'No clear pattern' },
      { value: 4, label: 'Tend to sell winners faster' },
      { value: 5, label: 'Sell winners quickly, hold losers hoping for recovery' },
    ],
  },
  {
    id: 25,
    key: 'q25_post_decision_review',
    title: 'Post-Decision Review',
    biasType: 'hindsight_bias',
    question: 'After an investment outcome becomes clear, how do you feel?',
    icon: '🔮',
    note: 'Reverse scoring - Score 5 = High Hindsight Bias',
    options: [
      { value: 1, label: 'Systematically analyze what I couldn\'t have predicted' },
      { value: 2, label: 'Often learn from unexpected outcomes' },
      { value: 3, label: 'Sometimes surprised by outcomes' },
      { value: 4, label: 'Often feel I should have known this would happen' },
      { value: 5, label: 'Always think I knew this would happen' },
    ],
  },
];

// Export all questions
export const allQuestions = {
  capacity: riskCapacityQuestions,
  willingness: riskWillingnessQuestions,
  bias: behavioralBiasQuestions,
};
