import type { Metadata } from 'next'

const clauses = [
  {
    title: '1. Acceptance of Terms',
    detail:
      'By creating an account, purchasing credits, or accessing any Deep feature you agree to these Terms of Service and any policies referenced here. If you are using the platform on behalf of an organization, you confirm you have authority to bind that entity.',
  },
  {
    title: '2. Eligibility & Accounts',
    detail:
      'You must be at least 18 years old, reside in a jurisdiction where our services are permitted, and provide accurate registration information. Keep credentials confidential and notify us of any unauthorized use.',
  },
  {
    title: '3. Credits, Billing, and Refunds',
    detail:
      'Credits are required to run premium analyses, API calls, or AI tasks. Credits are non-transferable and expire only if your account is closed for more than 12 months. Purchases are final except where required by consumer protection laws.',
  },
  {
    title: '4. Market Data & Third-Party Content',
    detail:
      'Quotes, fundamentals, and news are sourced from third parties (e.g., Yahoo Finance). Deep does not guarantee accuracy, timeliness, or availability of this data and may suspend feeds without liability.',
  },
  {
    title: '5. Acceptable Use',
    detail:
      'Do not scrape, resell, or redistribute platform data. Do not attempt to bypass credit enforcement or security controls. Abusive or unlawful activity results in immediate suspension.',
  },
  {
    title: '6. AI & Insights Disclaimer',
    detail:
      'Outputs generated by AI assistants, strategy templates, or calculators are informational and do not constitute financial, investment, tax, or legal advice. You remain responsible for trading decisions.',
  },
  {
    title: '7. Limitation of Liability',
    detail:
      'To the maximum extent permitted by law Deep is not liable for indirect, incidental, or consequential damages, lost profits, or trading losses. Aggregate liability is limited to the fees paid in the preceding three months.',
  },
  {
    title: '8. Termination',
    detail:
      'You may close your account at any time. We may suspend or terminate access if you breach these terms or create material risk for the platform. Upon termination we will delete or anonymize personal data subject to legal retention requirements.',
  },
  {
    title: '9. Governing Law',
    detail:
      'These terms are governed by the laws of England and Wales, without regard to conflict-of-law principles. Disputes will be resolved exclusively in the courts of London, UK, unless mandatory consumer protection laws provide otherwise.',
  },
]

export const metadata: Metadata = {
  title: 'Terms of Service | Deep',
  description: 'Review the legal terms that govern your use of Deep and its credit-based analytics platform.',
}

export default function TermsPage() {
  return (
    <div className="bg-[#030508] text-white">
      <section className="mx-auto max-w-4xl px-6 py-16 space-y-8">
        <header>
          <p className="text-xs uppercase tracking-[0.3em] text-violet-400">Terms of Service</p>
          <h1 className="mt-4 text-4xl font-bold">The rules for using Deep</h1>
          <p className="mt-4 text-base text-white/70">
            Last updated: November 30, 2025. These terms describe your rights and responsibilities when accessing Deep, purchasing credits,
            or using any related APIs, emails, AI tooling, or market data.
          </p>
        </header>

        <div className="space-y-6">
          {clauses.map((clause) => (
            <article key={clause.title} className="rounded-2xl border border-white/5 bg-white/5 p-6">
              <h2 className="text-xl font-semibold text-white">{clause.title}</h2>
              <p className="mt-3 text-sm leading-relaxed text-white/70">{clause.detail}</p>
            </article>
          ))}
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 text-sm text-white/70">
          <p>
            Questions about these terms? Contact legal@deepinhq.com. For regulatory or audit requests please include your authority, case number,
            and requested scope so we can respond promptly.
          </p>
        </div>
      </section>
    </div>
  )
}
